### ISSUE TITLE
how long does it take to capture avi file?

### ISSUE THREAD

**Issue by gr816ox** [giocoal/hmdb51-two-stream-action-recognition#2]
Hello,
I was confused that data/rawframes&opticalflow_extraction.py takes so long (>15min, my gpu is 3060, ram is 14gb) and it just stay here everytime running it.
![image](https://user-images.githubusercontent.com/50945677/209474350-c439b062-557e-46f7-8f24-4d158fed0b93.png)
BTW, could you open a discussion in the repo?
Thank you very much for your help!

**Comment by giocoal** [comment]
Hi gr816ox!
The script takes a long time, especially for Optical Flow generation, a time that increases a lot if OpenCV Cuda-Enabled is not used.
As far as I remember (3070, 32gb ram) it took a whole day to generate everything, setting multiprocessing to 6 physical processors.
In case you can't generate them let me know, I can pass them directly to you!

**Comment by giocoal** [comment]
In the meantime, I took the opportunity to open a discussion in the repo!

**Comment by gr816ox** [comment]
Hi giocoal!
THX! I'm running the code on a cloud server, and it's very complicated to debug :(. 
Could you pass the data with google drive?
It's very kind of you to save me from the terrible debugging XD.

**Comment by giocoal** [comment]
I uploaded a .zip file containing the RGB frames and Optical Flow to Google Drive. The download link and instructions for using them can be found in the README of the repository.

I hope I have been of some help, I would be very pleased if you star ⭐ my repo if you feel like it :)

**Comment by gr816ox** [comment]
Sure! This is an very useful repo to me. Thanks again for your help!
