### ISSUE TITLE
convert_to_image function not found in the code "spatial_stream_cnn_finetuned.ipynb"

### ISSUE THREAD

**Issue by adasnew** [giocoal/hmdb51-two-stream-action-recognition#5]
Hi,

Please share the **convert_to_image** function.

Thanks,
Abhijit Das

**Comment by giocoal** [comment]
Thanks for the report! I'll try to tag the author of the notebook and see if he has any ideas @gianscuri

**Comment by giocoal** [comment]
I consulted with my colleague, you can safely ignore that portion of the code (which should be commented out)
